### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by omidfathi** [sightmachine/OpenOPC#12]
Hi
when i try to install OpenOPC by "python3 setup.py install" i get these messages :

running install
running bdist_egg
running egg_info
writing OpenOPC.egg-info/PKG-INFO
writing dependency_links to OpenOPC.egg-info/dependency_links.txt
writing top-level names to OpenOPC.egg-info/top_level.txt
reading manifest file 'OpenOPC.egg-info/SOURCES.txt'
writing manifest file 'OpenOPC.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/OpenOPC
copying build/lib/OpenOPC/OpenOPCService.py -> build/bdist.linux-x86_64/egg/OpenOPC
copying build/lib/OpenOPC/opc.py -> build/bdist.linux-x86_64/egg/OpenOPC
copying build/lib/OpenOPC/SystemHealth.py -> build/bdist.linux-x86_64/egg/OpenOPC
copying build/lib/OpenOPC/__init__.py -> build/bdist.linux-x86_64/egg/OpenOPC
byte-compiling build/bdist.linux-x86_64/egg/OpenOPC/OpenOPCService.py to OpenOPCService.cpython-38.pyc
  File "build/bdist.linux-x86_64/egg/OpenOPC/OpenOPCService.py", line 27
    print 'Pyro module required (http://pyro.sourceforge.net/)'
          ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-x86_64/egg/OpenOPC/opc.py to opc.cpython-38.pyc
  File "build/bdist.linux-x86_64/egg/OpenOPC/opc.py", line 78
    print 'OpenOPC Command Line Client', OpenOPC.__version__
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('OpenOPC Command Line Client', OpenOPC.__version__)?

byte-compiling build/bdist.linux-x86_64/egg/OpenOPC/SystemHealth.py to SystemHealth.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/OpenOPC/__init__.py to __init__.cpython-38.pyc
  File "build/bdist.linux-x86_64/egg/OpenOPC/__init__.py", line 167
    except pythoncom.com_error, err:
                              ^
SyntaxError: invalid syntax

creating build/bdist.linux-x86_64/egg/EGG-INFO
copying OpenOPC.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying OpenOPC.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying OpenOPC.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying OpenOPC.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying OpenOPC.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
creating 'dist/OpenOPC-1.2-py3.8.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing OpenOPC-1.2-py3.8.egg
removing '/usr/local/lib/python3.8/dist-packages/OpenOPC-1.2-py3.8.egg' (and everything under it)
creating /usr/local/lib/python3.8/dist-packages/OpenOPC-1.2-py3.8.egg
Extracting OpenOPC-1.2-py3.8.egg to /usr/local/lib/python3.8/dist-packages
  File "/usr/local/lib/python3.8/dist-packages/OpenOPC-1.2-py3.8.egg/OpenOPC/OpenOPCService.py", line 27
    print 'Pyro module required (http://pyro.sourceforge.net/)'
          ^
SyntaxError: invalid syntax

  File "/usr/local/lib/python3.8/dist-packages/OpenOPC-1.2-py3.8.egg/OpenOPC/__init__.py", line 167
    except pythoncom.com_error, err:
                              ^
SyntaxError: invalid syntax

  File "/usr/local/lib/python3.8/dist-packages/OpenOPC-1.2-py3.8.egg/OpenOPC/opc.py", line 78
    print 'OpenOPC Command Line Client', OpenOPC.__version__
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('OpenOPC Command Line Client', OpenOPC.__version__)?

OpenOPC 1.2 is already the active version in easy-install.pth

Installed /usr/local/lib/python3.8/dist-packages/OpenOPC-1.2-py3.8.egg
Processing dependencies for OpenOPC==1.2
Finished processing dependencies for OpenOPC==1.2

**Comment by elyancorrea** [comment]
Did you install Pyro module on python?

**Comment by omidfathi** [comment]
Yes, i did

**Comment by omidfathi** [comment]
Hello again
i wrote this program in a *.py file:

import OpenOPC
opc = OpenOPC.client()
opc.connect("opc.tcp://o-fathi:53530/OPCUA/SimulationServer")
print(opc.list())


but when i run this i get this error:

Traceback (most recent call last):
  File "path", line 1, in <module>
    import OpenOPC
  File "/home/oem/anaconda3/lib/python3.9/site-packages/OpenOPC/__init__.py", line 162
    except pythoncom.com_error, err:
                              ^
SyntaxError: invalid syntax


and i use it in ubuntu 20
